parameters:
    spipu.configuration.file.allow: true
    spipu.configuration.file.path: "public/media/config/"
    spipu.configuration.file.url: "media/config/"

services:
    # Generic Declaration
    Spipu\ConfigurationBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,SpipuConfigurationBundle.php}'
        autowire: true
        autoconfigure: true

    # Manager
    Spipu\ConfigurationBundle\Service\ConfigurationManager:
        public: true
        autowire: true
        arguments:
            $container: '@service_container'

    # Role Definition
    Spipu\ConfigurationBundle\Service\RoleDefinition:
        tags: ['spipu.user.role']

    # Internal Services
    Spipu\ConfigurationBundle\Command\ShowCommand:
        tags: ['console.command']
        autowire: true

    Spipu\ConfigurationBundle\Repository\ConfigurationRepository:
        tags: ['doctrine.repository_service']
        arguments:
            - '@doctrine'

    Spipu\ConfigurationBundle\Field\:
        resource: '../../Field'
        tags: ['spipu.configuration.field']
        autowire: true

    Spipu\ConfigurationBundle\Field\FieldBoolean:
        tags: ['spipu.configuration.field']
        arguments:
            $container: '@service_container'

    Spipu\ConfigurationBundle\Field\FieldSelect:
        tags: ['spipu.configuration.field']
        arguments:
            $container: '@service_container'

    Spipu\ConfigurationBundle\Service\FieldList:
        arguments:
            - !tagged 'spipu.configuration.field'

    Spipu\ConfigurationBundle\Ui\ConfigurationForm:
        autowire: true

    Spipu\ConfigurationBundle\Ui\ConfigurationGrid:
        autowire: true

    Spipu\ConfigurationBundle\Ui\Grid\DataProvider:
        public: true
        autowire: true

    Spipu\ConfigurationBundle\Twig\ConfigurationExtension:
        tags:
            - "twig.extension"
        autowire: true
