services:
    # Generic Declaration
    Spipu\ConfigurationBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,SpipuConfigurationBundle.php}'
        autowire: true
        autoconfigure: true

    # File Manager
    Spipu\ConfigurationBundle\Service\FileManagerInterface:
        class: Spipu\ConfigurationBundle\Service\FileManager
        arguments:
            $allowFiles: true
            $projectDir: '%kernel.project_dir%'
            $filePath:   'public/media/config/'
            $fileUrl:    'media/config/'

    # Options
    Spipu\ConfigurationBundle\Form\Options\ScopeOptions:
        public: true
        autowire: true
        arguments:
            $scopeList: '@spipu.configuration.service.scope_list'

    # Configuration Manager
    Spipu\ConfigurationBundle\Service\ConfigurationManager:
        public: true
        autowire: true

    # Configuration Definitions
    Spipu\ConfigurationBundle\Service\Definitions:
        public: true
        autowire: true
        arguments:
            $container: '@service_container'

    # Role Definition
    Spipu\ConfigurationBundle\Service\RoleDefinition:
        tags: ['spipu.user.role']

    # Internal Services
    Spipu\ConfigurationBundle\Command\ShowCommand:
        tags: ['console.command']
        autowire: true

    Spipu\ConfigurationBundle\Repository\ConfigurationRepository:
        tags: ['doctrine.repository_service']
        arguments:
            - '@doctrine'

    Spipu\ConfigurationBundle\Field\:
        resource: '../../Field'
        tags: ['spipu.configuration.field']
        autowire: true

    Spipu\ConfigurationBundle\Field\FieldBoolean:
        tags: ['spipu.configuration.field']
        arguments:
            $container: '@service_container'

    Spipu\ConfigurationBundle\Field\FieldSelect:
        tags: ['spipu.configuration.field']
        arguments:
            $container: '@service_container'

    Spipu\ConfigurationBundle\Service\FieldList:
        arguments:
            - !tagged 'spipu.configuration.field'

    Spipu\ConfigurationBundle\Ui\ConfigurationForm:
        autowire: true

    Spipu\ConfigurationBundle\Ui\ConfigurationGrid:
        autowire: true

    Spipu\ConfigurationBundle\Ui\Grid\DataProvider:
        public: true
        autowire: true

    Spipu\ConfigurationBundle\Twig\ConfigurationExtension:
        tags:
            - "twig.extension"
        autowire: true

    # Scope management
    spipu.configuration.service.scope_list:
        class: Spipu\ConfigurationBundle\Service\ScopeList
        autowire: true

    Spipu\ConfigurationBundle\Service\ScopeService:
        autowire: true
        arguments:
            $scopeList: '@spipu.configuration.service.scope_list'
